# colors.py

# Hexadecimal Color CONSTANTS Section.
# Basic Hexadecimal Color CONSTANTS Section.
RED   = "#FF0000"
GREEN = "#00FF00"
BLUE  = "#0000FF"

BLACK = "#000000"
WHITE = "#FFFFFF"

ALPHA = GREEN

# Custom Hexadecimal Color CONSTANTS Section.
GRAY  = "#333333"
DARK_GRAY = "#121212"
DARK_GREEN = "#005500"

# Default Hexadecimal CONSTANTS Colors Section.
DARK_MODE_COLOR  = BLACK
LIGHT_MODE_COLOR = WHITE

DEFAULT_PAGE_COLOR = GRAY
DEFAULT_SCREEN_ABSTRACTION_COLOR = DARK_MODE_COLOR

DEFAULT_NAVBAR_COLOR = BLACK
DEFAULT_NAVBAR_BACKGROUND_COLOR = WHITE